<?php

namespace CDP\BookingBundle\Repository;

/**
 * ticketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
	public function countByDate($date)
  	{
    	$qb = $this->createQueryBuilder('t');
    	$qb->select('COUNT(t)');
    	$qb->where('t.date = :date');
    	$qb->setParameter('date', $date);
    	return $qb->getQuery()->getSingleScalarResult();
  	}
}
