cdp_booking_homepage:
    path:     /
    defaults: { _controller: CDPBookingBundle:Ticket:index }

cdp_booking_new:
    path:     /new
    defaults: { _controller: CDPBookingBundle:Ticket:new }

cdp_booking_add:
    path:     /add
    defaults: { _controller: CDPBookingBundle:Ticket:add }

cdp_booking_save:
    path:     /save
    defaults: { _controller: CDPBookingBundle:Ticket:save }
