services:
    cdp_booking.validator.datedispo:
        class: CDP\BookingBundle\Validator\DateDispoValidator
        arguments: ["@request_stack", "@doctrine.orm.entity_manager", "@service_container"]
        tags:
            - { name: validator.constraint_validator, alias: cdp_booking_datedispo }
